### ISSUE TITLE
Generate a wpml-config.xml file

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/lawyeria-lite#33]
Generating a wpml-config.xml file for better translations.

**Comment by rodica-andronache** [comment]
@HardeepAsrani thanks :) in general, I don't think we plan on to keep updating this theme, as we have lawyeriax lite. But, if you want us to put this update, can you please check if it passes all Theme Check tests? so we can upload it on wporg

**Comment by rodica-andronache** [comment]
@HardeepAsrani there are errors here, so we can't update it.

Warning: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are lawyeria-lite, tgmpa, zerif-lite, >Home Page to start fresh. We\ll do better next time.
WARNING: Found a translation function that has an incorrect number of arguments. Function __, with the arguments 'Oops, I screwed up and you discovered my fatal flaw. Well, we\'re not all perfect, but we try. Can you try this again or maybe visit our WARNING: .git Hidden Files or Folders found.
