### ISSUE TITLE
Menu limit too small

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/lawyeria-lite#6]
In meniu incap maxim 7-8 link-uri, poate ar trebui sa micim spatiul dintre ele sau sa marim putin wrapper-ul.

**Comment by mariusghitulescu** [comment]
Aceeasi problema exista si la PRO.

**Comment by robi09** [comment]
Ideea este ca trebuie marit spatiul din js-ul care micsoreaza meniul.

**Comment by mariusghitulescu** [comment]
Trebuie marita limita de 800 din /includes/scripts.js

var full_width = 0;

jQuery(“nav ul:first > li”).each(function( index ) {
if((jQuery(this).width() + full_width) > 800) {
jQuery(this).remove();
}
full_width = full_width + jQuery(this).width();
});

**Comment by robi09** [comment]
@robciucioan  sa rezolvi aici cum am discutat te rog.
